version: '3'

services:

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper

  kafka:
    image: wurstmeister/kafka:2.13-2.7.1
    container_name: kafka
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "posts:1:1"

  readability:
    image: phpdockerio/readability-js-server
    container_name: readability

  scraper:
    build: .
    container_name: scraper
    environment:
      SCR_READABILITY_URI: "http://readability:3000"
      SCR_KAFKA_ADDRESS: "kafka:9092"
      SCR_LOGGING_LEVEL: "debug"